<?php

namespace Stripedesk\Services;

use Dompdf\Dompdf;
use Dompdf\Options;

/**
 * Renders a payment receipt as PDF (Dompdf).
 */
final class Receipt_pdf_service
{
    private $ci;

    public function __construct($ci)
    {
        $this->ci = $ci;
    }

    /**
     * @param array $data Same shape as Receipt_detail_dto::to_array() plus optional line_items (list of arrays with product_name, quantity, unit_price)
     *
     * @return string PDF binary
     */
    public function render_binary(array $data)
    {
        $html = $this->build_html($data);
        $options = new Options();
        $options->set('isRemoteEnabled', false);
        $options->set('defaultFont', 'DejaVu Sans');
        $dompdf = new Dompdf($options);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
        return $dompdf->output();
    }

    private function build_html(array $data)
    {
        $brand = function_exists('sd_env') ? (string) sd_env('APP_NAME', 'StripeDesk') : 'StripeDesk';
        $receipt_number = $this->esc(isset($data['receipt_number']) ? $data['receipt_number'] : '');
        $amount_paid = $this->esc(isset($data['amount_paid']) ? $data['amount_paid'] : '');
        $paid_at = $this->esc(isset($data['paid_at']) ? $data['paid_at'] : '—');
        $pi = isset($data['stripe_payment_intent']) && $data['stripe_payment_intent'] !== null
            ? $this->esc((string) $data['stripe_payment_intent'])
            : '—';
        $inv = isset($data['invoice']) && is_array($data['invoice']) ? $data['invoice'] : array();
        $inv_num = $this->esc(isset($inv['invoice_number']) ? $inv['invoice_number'] : '—');
        $inv_total = $this->esc(isset($inv['total_amount']) ? $inv['total_amount'] : '—');
        $inv_status = $this->esc(isset($inv['status']) ? $inv['status'] : '—');

        $rows = '';
        if (isset($data['line_items']) && is_array($data['line_items']))
        {
            foreach ($data['line_items'] as $li)
            {
                if ( ! is_array($li))
                {
                    continue;
                }
                $name = $this->esc(isset($li['product_name']) ? $li['product_name'] : '');
                $qty = $this->esc(isset($li['quantity']) ? (string) $li['quantity'] : '1');
                $price = $this->esc(isset($li['unit_price']) ? (string) $li['unit_price'] : '');
                $rows .= '<tr><td>' . $name . '</td><td style="text-align:right">' . $qty . '</td><td style="text-align:right">' . $price . '</td></tr>';
            }
        }

        if ($rows === '')
        {
            $rows = '<tr><td colspan="3" style="color:#666">Line items not available.</td></tr>';
        }

        return '<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>
body{font-family:DejaVu Sans,sans-serif;font-size:12px;color:#111;margin:40px;}
h1{font-size:20px;margin:0 0 8px;}
.sub{color:#555;margin:0 0 24px;}
table{width:100%;border-collapse:collapse;margin-top:16px;}
th,td{border:1px solid #ccc;padding:8px;}
th{background:#f2f2f2;text-align:left;}
.meta{margin-top:24px;line-height:1.6;}
.footer{margin-top:40px;font-size:10px;color:#888;}
</style></head><body>'
            . '<h1>' . $this->esc($brand) . '</h1>'
            . '<p class="sub">Receipt ' . $receipt_number . '</p>'
            . '<table><thead><tr><th>Item</th><th style="text-align:right">Qty</th><th style="text-align:right">Unit price</th></tr></thead><tbody>'
            . $rows
            . '</tbody></table>'
            . '<div class="meta">'
            . '<strong>Amount paid:</strong> ' . $amount_paid . '<br/>'
            . '<strong>Paid at:</strong> ' . $paid_at . '<br/>'
            . '<strong>Invoice:</strong> ' . $inv_num . ' &nbsp;|&nbsp; <strong>Total:</strong> ' . $inv_total
            . ' &nbsp;|&nbsp; <strong>Status:</strong> ' . $inv_status . '<br/>'
            . '<strong>Payment reference:</strong> ' . $pi
            . '</div>'
            . '<p class="footer">Generated by ' . $this->esc($brand) . '.</p>'
            . '</body></html>';
    }

    private function esc($value)
    {
        return htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    }
}
