<?php

namespace Stripedesk\Services;

/**
 * Builds a single-page HTML receipt document (Single Responsibility: markup only, no PDF engine).
 */
final class Receipt_html_document_builder
{
    /**
     * @param array $data Same shape as Receipt_detail_dto::to_array() plus optional line_items
     *
     * @return string UTF-8 HTML
     */
    public function build(array $data)
    {
        $brand = $this->brand_name();
        $receipt_number = $this->esc($this->string_at($data, 'receipt_number'));
        $amount_paid = $this->esc($this->string_at($data, 'amount_paid'));
        $paid_at = $this->esc($this->string_at($data, 'paid_at', '—'));
        $pi = $this->payment_intent_display($data);
        $inv = isset($data['invoice']) && is_array($data['invoice']) ? $data['invoice'] : array();
        $inv_num = $this->esc($this->string_at($inv, 'invoice_number', '—'));
        $inv_total = $this->esc($this->string_at($inv, 'total_amount', '—'));
        $inv_status = $this->esc($this->string_at($inv, 'status', '—'));

        $rows = $this->line_item_rows($data);
        if ($rows === '')
        {
            $rows = '<tr><td colspan="3" style="color:#666">Line items not available.</td></tr>';
        }

        return $this->wrap_document(
            $brand,
            $receipt_number,
            $rows,
            $amount_paid,
            $paid_at,
            $inv_num,
            $inv_total,
            $inv_status,
            $pi
        );
    }

    private function brand_name()
    {
        if (function_exists('sd_env'))
        {
            return (string) sd_env('APP_NAME', 'StripeDesk');
        }

        return 'StripeDesk';
    }

    private function payment_intent_display(array $data)
    {
        if ( ! isset($data['stripe_payment_intent']) || $data['stripe_payment_intent'] === null)
        {
            return '—';
        }

        return $this->esc((string) $data['stripe_payment_intent']);
    }

    private function line_item_rows(array $data)
    {
        if ( ! isset($data['line_items']) || ! is_array($data['line_items']))
        {
            return '';
        }

        $rows = '';
        foreach ($data['line_items'] as $li)
        {
            if ( ! is_array($li))
            {
                continue;
            }
            $name = $this->esc($this->string_at($li, 'product_name'));
            $qty = $this->esc($this->string_at($li, 'quantity', '1'));
            $price = $this->esc($this->string_at($li, 'unit_price'));
            $rows .= '<tr><td>' . $name . '</td><td style="text-align:right">' . $qty . '</td><td style="text-align:right">' . $price . '</td></tr>';
        }

        return $rows;
    }

    private function wrap_document(
        $brand,
        $receipt_number,
        $rows,
        $amount_paid,
        $paid_at,
        $inv_num,
        $inv_total,
        $inv_status,
        $pi
    ) {
        $brand_esc = $this->esc($brand);

        return '<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>
body{font-family:DejaVu Sans,sans-serif;font-size:12px;color:#111;margin:40px;}
h1{font-size:20px;margin:0 0 8px;}
.sub{color:#555;margin:0 0 24px;}
table{width:100%;border-collapse:collapse;margin-top:16px;}
th,td{border:1px solid #ccc;padding:8px;}
th{background:#f2f2f2;text-align:left;}
.meta{margin-top:24px;line-height:1.6;}
.footer{margin-top:40px;font-size:10px;color:#888;}
</style></head><body>'
            . '<h1>' . $brand_esc . '</h1>'
            . '<p class="sub">Receipt ' . $receipt_number . '</p>'
            . '<table><thead><tr><th>Item</th><th style="text-align:right">Qty</th><th style="text-align:right">Unit price</th></tr></thead><tbody>'
            . $rows
            . '</tbody></table>'
            . '<div class="meta">'
            . '<strong>Amount paid:</strong> ' . $amount_paid . '<br/>'
            . '<strong>Paid at:</strong> ' . $paid_at . '<br/>'
            . '<strong>Invoice:</strong> ' . $inv_num . ' &nbsp;|&nbsp; <strong>Total:</strong> ' . $inv_total
            . ' &nbsp;|&nbsp; <strong>Status:</strong> ' . $inv_status . '<br/>'
            . '<strong>Payment reference:</strong> ' . $pi
            . '</div>'
            . '<p class="footer">Generated by ' . $brand_esc . '.</p>'
            . '</body></html>';
    }

    private function string_at(array $data, $key, $default = '')
    {
        return isset($data[$key]) ? (string) $data[$key] : $default;
    }

    private function esc($value)
    {
        return htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    }
}
